export const PRIMARY_CATEGORY = [
  "thiên nhiên",
  "lịch sử",
  "văn hóa",
  "kiến trúc",
  "tâm linh",
  "ẩm thực",
  "giải trí",
  "mua sắm",
  "nghệ thuật",
  "khoa học / bảo tàng",
  "thành phố",
  "di sản",
  "lễ hội",
  "sinh thái",
  "nghỉ dưỡng",
  "đời sống địa phương",
  "văn hóa dân gian",
  "kiến trúc tôn giáo",
];

export const ATTRIBUTES = [
  "cảnh đẹp",
  "biểu tượng",
  "hoài niệm",
  "hiện đại",
  "thư giãn",
  "lãng mạn",
  "mạo hiểm",
  "truyền thống",
  "yên bình",
  "sầm uất",
  "cổ kính",
  "độc đáo",
  "huyền bí",
  "xanh mát",
  "hoành tráng",
  "thơ mộng",
  "nguyên sơ",
  "check-in đẹp",
  "náo nhiệt",
  "sang trọng",
  "bình dân",
];

export const ACTIVITIES = [
  "tham quan",
  "chụp ảnh",
  "ngắm cảnh",
  "dạo phố",
  "đi lễ chùa",
  "tham quan bảo tàng",
  "tham quan di tích",
  "thưởng thức ẩm thực",
  "nightlife",
  "workshop thủ công",
];

export const PHYSICAL_TYPE = [
  "núi",
  "biển",
  "sông",
  "hồ",
  "đồi",
  "rừng",
  "bảo tàng",
  "di tích lịch sử",
  "phố cổ",
  "chùa / đền / miếu",
  "nhà hàng",
  "quán cà phê",
  "resort",
  "công viên",
  "bãi biển",
];
